version: '1.0.{build}'
skip_tags: true
image: Visual Studio 2015
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
  - ps: dotnet --info
build_script:
- ps: .\build.ps1
test: off
artifacts:
  - path: artifacts/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: ov1HE744hnP6J5umXYTQwuegvkI9qn4pNBZTsSvPO+9LOSktdYHTAnSUhMBZha/w
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master